'use client';

import React, { useState, useEffect } from 'react';
import { X, Copy, Check, Settings, TestTube, Shield, Send, Key, ChevronDown, ChevronRight } from 'lucide-react';
import { useAuth } from '@/contexts/AuthContext';

interface DestinationWebhookDetailModalProps {
  isOpen: boolean;
  onClose: () => void;
  destinationKey: string;
  agentId: string;
  onSave?: () => void;
}

interface DestinationWebhookDetails {
  destinationKey: string;
  name: string;
  description: string;
  category: 'sms' | 'email' | 'phone';
  endpoint: {
    url: string;
    method: string;
    headers?: Record<string, string>;
    authType: 'none' | 'bearer' | 'basic' | 'api_key' | 'signing_secret';
    authConfig?: {
      token?: string;
      username?: string;
      password?: string;
      apiKey?: string;
      apiKeyHeader?: string;
    };
  };
  payloadTemplate: string;
  isActive: boolean;
  createdAt: string;
  updatedAt: string;
  signingSecret?: string;
}

type MenuSection = 'general' | 'test' | 'auth';

export default function DestinationWebhookDetailModal({
  isOpen,
  onClose,
  destinationKey,
  agentId,
  onSave
}: DestinationWebhookDetailModalProps) {
  const { tenant, getToken } = useAuth();
  const [webhook, setWebhook] = useState<DestinationWebhookDetails | null>(null);
  const [loading, setLoading] = useState(false);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [activeSection, setActiveSection] = useState<MenuSection>('general');
  const [copiedKey, setCopiedKey] = useState(false);
  const [copiedSigningKey, setCopiedSigningKey] = useState(false);
  const [testPayload, setTestPayload] = useState('');
  const [testResponse, setTestResponse] = useState('');
  const [testing, setTesting] = useState(false);
  const [showRequestExample, setShowRequestExample] = useState(false);
  const [showResponseExample, setShowResponseExample] = useState(false);

  // Form state
  const [formData, setFormData] = useState({
    name: '',
    description: '',
    url: '',
    authType: 'none' as 'none' | 'signing_secret',
    authConfig: {
      token: '',
      username: '',
      password: '',
      apiKey: '',
      apiKeyHeader: ''
    },
    isActive: true
  });

  useEffect(() => {
    if (isOpen && destinationKey && agentId && tenant?.id) {
      fetchWebhookDetails();
    }
  }, [isOpen, destinationKey, agentId, tenant?.id]);

  const fetchWebhookDetails = async () => {
    if (!tenant?.id) return;
    
    setLoading(true);
    setError(null);
    
    try {
      const token = await getToken();
      if (!token) {
        throw new Error('Authentication token not available');
      }

      const apiUrl = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:8000';
      const response = await fetch(
        `${apiUrl}/api/destination-webhooks/destination/${tenant.id}/${agentId}/${destinationKey}`,
        {
          method: 'GET',
          headers: {
            'Content-Type': 'application/json',
            'Authorization': `Bearer ${token}`
          }
        }
      );

      if (!response.ok) {
        throw new Error(`Failed to fetch webhook details: ${response.statusText}`);
      }

      const result = await response.json();
      
      if (result.success && result.data.webhook) {
        const webhookData = result.data.webhook;
        setWebhook(webhookData);
        
        // Populate form data
        setFormData({
          name: webhookData.name || '',
          description: webhookData.description || '',
          url: webhookData.endpoint?.url || '',
          authType: webhookData.endpoint?.authType || 'none',
          authConfig: {
            token: webhookData.endpoint?.authConfig?.token || '',
            username: webhookData.endpoint?.authConfig?.username || '',
            password: webhookData.endpoint?.authConfig?.password || '',
            apiKey: webhookData.endpoint?.authConfig?.apiKey || '',
            apiKeyHeader: webhookData.endpoint?.authConfig?.apiKeyHeader || ''
          },
          isActive: webhookData.isActive !== undefined ? webhookData.isActive : true
        });

        // Set up test payload matching the actual backend format
        const mockPayload = {
          message: `Test ${webhookData.category} message generated by AI agent`,
          contactId: "contact_test123",
          agentId: agentId,
          tenantId: tenant?.id || "tenant_test456",
          timestamp: new Date().toISOString(),
          messageId: "msg_test789",
          caseId: "case_test012",
          conversationId: "conv_test345",
          fromPhone: "+1987654321",
          toPhone: "+1234567890",
          messageType: webhookData.category,
          contact: {
            contactId: "contact_test123",
            fullName: "Test User",
            firstName: "Test",
            lastName: "User",
            email: "test.user@example.com",
            phoneNumber: "+1234567890",
            name: "Test User"
          }
        };
        setTestPayload(JSON.stringify(mockPayload, null, 2));
      } else {
        throw new Error('Webhook not found');
      }
    } catch (error) {
      console.error('Error fetching webhook details:', error);
      setError(error instanceof Error ? error.message : 'Failed to fetch webhook details');
    } finally {
      setLoading(false);
    }
  };

  const handleSave = async () => {
    if (!webhook || !tenant?.id) return;

    setSaving(true);
    setError(null);

    try {
      const token = await getToken();
      if (!token) {
        throw new Error('Authentication token not available');
      }

      const apiUrl = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:8000';
      const endpoint = `${apiUrl}/api/destination-webhooks/setup-${webhook.category}-destination/${tenant.id}/${agentId}`;
      
      const payload = {
        name: formData.name,
        description: formData.description,
        endpoint: {
          url: formData.url,
          method: 'POST',
          authType: formData.authType,
          authConfig: formData.authType !== 'none' ? formData.authConfig : undefined
        },
        isActive: formData.isActive,
        destinationKey: webhook.destinationKey
      };

      const response = await fetch(endpoint, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${token}`
        },
        body: JSON.stringify(payload)
      });

      if (!response.ok) {
        throw new Error(`Failed to update webhook: ${response.statusText}`);
      }

      const result = await response.json();

      if (result.success) {
        onSave?.();
        onClose();
      } else {
        throw new Error(result.message || 'Failed to update webhook');
      }
    } catch (error) {
      console.error('Error saving webhook:', error);
      setError(error instanceof Error ? error.message : 'Failed to save webhook');
    } finally {
      setSaving(false);
    }
  };

  const handleInputChange = (field: string, value: any) => {
    if (field.startsWith('authConfig.')) {
      const authField = field.split('.')[1];
      setFormData(prev => ({
        ...prev,
        authConfig: {
          ...prev.authConfig,
          [authField]: value
        }
      }));
    } else {
      setFormData(prev => ({
        ...prev,
        [field]: value
      }));
    }
  };

  const copyToClipboard = async (text: string, type: 'key' | 'signing') => {
    try {
      await navigator.clipboard.writeText(text);
      if (type === 'key') {
        setCopiedKey(true);
        setTimeout(() => setCopiedKey(false), 2000);
      } else {
        setCopiedSigningKey(true);
        setTimeout(() => setCopiedSigningKey(false), 2000);
      }
    } catch (err) {
      console.error('Failed to copy:', err);
    }
  };

  const handleTestWebhook = async () => {
    if (!webhook || !tenant?.id) return;

    setTesting(true);
    setTestResponse('');

    try {
      const token = await getToken();
      if (!token) {
        throw new Error('Authentication token not available');
      }

      let customPayload;
      try {
        customPayload = JSON.parse(testPayload);
      } catch (parseError) {
        throw new Error('Invalid JSON in test payload');
      }

      const apiUrl = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:8000';
      const response = await fetch(
        `${apiUrl}/api/destination-webhooks/destination/${tenant.id}/${agentId}/${webhook.destinationKey}/test`,
        {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            'Authorization': `Bearer ${token}`
          },
          body: JSON.stringify({ customPayload })
        }
      );

      const result = await response.json();

      if (result.success) {
        setTestResponse(JSON.stringify({
          status: 'success',
          statusCode: result.data.statusCode,
          timeTaken: `${result.data.timeTaken}ms`,
          response: result.data.response,
          message: result.message
        }, null, 2));
      } else {
        setTestResponse(JSON.stringify({
          status: 'error',
          statusCode: result.data?.statusCode || response.status,
          error: result.error || 'Test failed',
          message: result.message,
          response: result.data?.response
        }, null, 2));
      }
    } catch (error) {
      setTestResponse(JSON.stringify({
        status: 'error',
        error: 'Network or parsing error',
        details: error instanceof Error ? error.message : 'Unknown error'
      }, null, 2));
    } finally {
      setTesting(false);
    }
  };

  const menuItems = [
    { id: 'general', label: 'General', icon: Settings },
    { id: 'test', label: 'Test', icon: TestTube },
    { id: 'auth', label: 'Authentication', icon: Shield }
  ];

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
      <div className="bg-white rounded-lg shadow-xl w-full max-w-5xl max-h-[90vh] overflow-hidden flex">
        {/* Sidebar Menu */}
        <div className="w-64 bg-gray-50 border-r border-gray-200 p-6">
          <div className="flex justify-between items-center mb-6">
            <h2 className="text-lg font-semibold text-gray-900">Destination Webhook</h2>
            <button
              onClick={onClose}
              className="text-gray-400 hover:text-gray-600"
            >
              <X className="w-5 h-5" />
            </button>
          </div>

          {/* Webhook Info */}
          {webhook && (
            <div className="bg-purple-50 border border-purple-200 rounded-lg p-4 mb-6">
              <div className="flex items-center justify-between mb-2">
                <span className="text-sm font-medium text-purple-900">Destination Key</span>
                <button
                  onClick={() => copyToClipboard(webhook.destinationKey, 'key')}
                  className="text-purple-600 hover:text-purple-800"
                >
                  {copiedKey ? <Check className="w-4 h-4" /> : <Copy className="w-4 h-4" />}
                </button>
              </div>
              <code className="text-xs text-purple-700 font-mono break-all">
                {webhook.destinationKey}
              </code>
              <div className="mt-2 text-xs text-purple-600">
                Category: <span className="capitalize">{webhook.category}</span>
              </div>
            </div>
          )}

          {/* Navigation Menu */}
          <nav className="space-y-2">
            {menuItems.map((item) => {
              const Icon = item.icon;
              return (
                <button
                  key={item.id}
                  onClick={() => setActiveSection(item.id as MenuSection)}
                  className={`w-full flex items-center px-3 py-2 text-sm font-medium rounded-md transition-colors ${
                    activeSection === item.id
                      ? 'bg-purple-100 text-purple-900 border border-purple-200'
                      : 'text-gray-600 hover:text-gray-900 hover:bg-gray-100'
                  }`}
                >
                  <Icon className="w-4 h-4 mr-3" />
                  {item.label}
                </button>
              );
            })}
          </nav>
        </div>

        {/* Main Content */}
        <div className="flex-1 flex flex-col">
          {loading ? (
            <div className="flex-1 flex items-center justify-center">
              <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-purple-600"></div>
              <span className="ml-3 text-gray-600">Loading webhook details...</span>
            </div>
          ) : error ? (
            <div className="flex-1 p-6">
              <div className="bg-red-50 border border-red-200 rounded-md p-4">
                <p className="text-red-600">{error}</p>
              </div>
            </div>
          ) : webhook ? (
            <>
              {/* Content Area */}
              <div className="flex-1 p-6 overflow-y-auto">
                {/* General Section */}
                {activeSection === 'general' && (
                  <div className="space-y-6">
                    <div>
                      <h3 className="text-lg font-medium text-gray-900 mb-4">General Configuration</h3>
                      
                      <div className="space-y-4">
                        <div>
                          <label className="block text-sm font-medium text-gray-700 mb-2">
                            Name
                          </label>
                          <input
                            type="text"
                            value={formData.name}
                            onChange={(e) => handleInputChange('name', e.target.value)}
                            className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-purple-500 focus:border-purple-500"
                          />
                        </div>

                        <div>
                          <label className="block text-sm font-medium text-gray-700 mb-2">
                            Description
                          </label>
                          <textarea
                            value={formData.description}
                            onChange={(e) => handleInputChange('description', e.target.value)}
                            rows={3}
                            className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-purple-500 focus:border-purple-500"
                          />
                        </div>

                        <div>
                          <label className="block text-sm font-medium text-gray-700 mb-2">
                            Endpoint URL
                          </label>
                          <input
                            type="url"
                            value={formData.url}
                            onChange={(e) => handleInputChange('url', e.target.value)}
                            className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-purple-500 focus:border-purple-500"
                          />
                        </div>

                        <div>
                          <label className="flex items-center">
                            <input
                              type="checkbox"
                              checked={formData.isActive}
                              onChange={(e) => handleInputChange('isActive', e.target.checked)}
                              className="h-4 w-4 text-purple-600 focus:ring-purple-500 border-gray-300 rounded"
                            />
                            <span className="ml-2 text-sm font-medium text-gray-700">
                              Active
                            </span>
                          </label>
                        </div>
                      </div>
                    </div>

                    {/* Usage Examples */}
                    <div className="space-y-4">
                      <h4 className="text-md font-medium text-gray-900">Usage Examples</h4>
                      
                      {/* Request Example */}
                      <div className="border border-gray-200 rounded-lg">
                        <button
                          onClick={() => setShowRequestExample(!showRequestExample)}
                          className="w-full px-4 py-3 text-left flex items-center justify-between bg-gray-50 hover:bg-gray-100 rounded-t-lg"
                        >
                          <span className="text-sm font-medium text-gray-700">
                            How to include destinationKey in your requests
                          </span>
                          {showRequestExample ? (
                            <ChevronDown className="w-4 h-4 text-gray-500" />
                          ) : (
                            <ChevronRight className="w-4 h-4 text-gray-500" />
                          )}
                        </button>
                        {showRequestExample && (
                          <div className="p-4 border-t border-gray-200">
                            <p className="text-sm text-gray-600 mb-3">
                              Include the destination key in your API requests to route content to this webhook:
                            </p>
                            <div className="bg-gray-900 rounded-md p-4">
                              <pre className="text-green-400 text-xs font-mono overflow-x-auto">
{`POST /api/agent-communication/sms/inbound
Content-Type: application/json
Authorization: Bearer YOUR_TOKEN

{
  "messageContent": "Hi, I'm interested in your services",
  "tenantId": "${tenant?.id || 'your-tenant-id'}",
  "contactId": "contact_abc123",
  "agentId": "${agentId}",
  "action": "general",
  "destinationKey": "${webhook?.destinationKey || 'your-destination-key'}",
  "from": "+1234567890",
  "to": "+1987654321",
  "conversationId": "conv_xyz789",
  "timestamp": "${new Date().toISOString()}"
}`}
                              </pre>
                            </div>
                            <p className="text-xs text-gray-500 mt-2">
                              When destinationKey is provided, the message content will be sent to your webhook instead of as an actual SMS/Email/Phone call.
                            </p>
                          </div>
                        )}
                      </div>

                      {/* Response Example */}
                      <div className="border border-gray-200 rounded-lg">
                        <button
                          onClick={() => setShowResponseExample(!showResponseExample)}
                          className="w-full px-4 py-3 text-left flex items-center justify-between bg-gray-50 hover:bg-gray-100 rounded-t-lg"
                        >
                          <span className="text-sm font-medium text-gray-700">
                            Payload format your webhook will receive
                          </span>
                          {showResponseExample ? (
                            <ChevronDown className="w-4 h-4 text-gray-500" />
                          ) : (
                            <ChevronRight className="w-4 h-4 text-gray-500" />
                          )}
                        </button>
                        {showResponseExample && (
                          <div className="p-4 border-t border-gray-200">
                            <p className="text-sm text-gray-600 mb-3">
                              Your webhook endpoint will receive a POST request with this payload structure:
                            </p>
                            <div className="bg-gray-900 rounded-md p-4">
                              <pre className="text-blue-400 text-xs font-mono overflow-x-auto">
{`{
  "message": "Thank you for contacting us! We've received your inquiry and will respond within 24 hours.",
  "contactId": "contact_xyz789",
  "agentId": "${agentId}",
  "tenantId": "${tenant?.id || 'your-tenant-id'}",
  "timestamp": "2025-09-21T16:30:00.000Z",
  "messageId": "msg_abc123def456",
  "caseId": "case_ghi789jkl012",
  "conversationId": "conv_abc123",
  "fromPhone": "+1987654321",
  "toPhone": "+1234567890",
  "messageType": "${webhook?.category || 'sms'}",
  "contact": {
    "contactId": "contact_xyz789",
    "fullName": "Jane Doe",
    "firstName": "Jane",
    "lastName": "Doe",
    "email": "jane.doe@example.com",
    "phoneNumber": "+1234567890",
    "name": "Jane Doe"
  }
}`}
                              </pre>
                            </div>
                            <p className="text-xs text-gray-500 mt-2">
                              Your endpoint should respond with a 200 status code to acknowledge receipt.
                            </p>
                          </div>
                        )}
                      </div>
                    </div>
                  </div>
                )}

                {/* Test Section */}
                {activeSection === 'test' && (
                  <div className="space-y-6">
                    <div>
                      <h3 className="text-lg font-medium text-gray-900 mb-4">Test Webhook</h3>
                      
                      <div className="space-y-4">
                        <div>
                          <label className="block text-sm font-medium text-gray-700 mb-2">
                            Test Payload
                          </label>
                          <textarea
                            value={testPayload}
                            onChange={(e) => setTestPayload(e.target.value)}
                            rows={8}
                            className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-purple-500 focus:border-purple-500 font-mono text-sm"
                          />
                        </div>

                        <button
                          onClick={handleTestWebhook}
                          disabled={testing || !formData.url}
                          className="flex items-center px-4 py-2 bg-purple-600 text-white rounded-md hover:bg-purple-700 disabled:opacity-50 disabled:cursor-not-allowed"
                        >
                          {testing ? (
                            <div className="animate-spin rounded-full h-4 w-4 border-b-2 border-white mr-2"></div>
                          ) : (
                            <Send className="w-4 h-4 mr-2" />
                          )}
                          {testing ? 'Sending...' : 'Send Test'}
                        </button>

                        {testResponse && (
                          <div>
                            <label className="block text-sm font-medium text-gray-700 mb-2">
                              Response
                            </label>
                            <textarea
                              value={testResponse}
                              readOnly
                              rows={6}
                              className="w-full px-3 py-2 border border-gray-300 rounded-md bg-gray-50 font-mono text-sm"
                            />
                          </div>
                        )}
                      </div>
                    </div>
                  </div>
                )}

                {/* Auth Section */}
                {activeSection === 'auth' && (
                  <div className="space-y-6">
                    <div>
                      <h3 className="text-lg font-medium text-gray-900 mb-4">Authentication</h3>
                      
                      <div className="space-y-4">
                        <div>
                          <label className="block text-sm font-medium text-gray-700 mb-2">
                            Authentication Type
                          </label>
                          <select
                            value={formData.authType}
                            onChange={(e) => handleInputChange('authType', e.target.value)}
                            className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-purple-500 focus:border-purple-500"
                          >
                            <option value="none">None</option>
                            <option value="signing_secret">Signing Secret (HMAC-SHA256)</option>
                          </select>
                        </div>

                        {formData.authType === 'signing_secret' && webhook?.signingSecret && (
                          <div className="bg-yellow-50 border border-yellow-200 rounded-lg p-4">
                            <div className="flex items-center justify-between mb-2">
                              <div className="flex items-center">
                                <Key className="w-4 h-4 text-yellow-600 mr-2" />
                                <span className="text-sm font-medium text-yellow-900">Signing Secret</span>
                              </div>
                              <button
                                onClick={() => copyToClipboard(webhook.signingSecret!, 'signing')}
                                className="text-yellow-600 hover:text-yellow-800"
                              >
                                {copiedSigningKey ? <Check className="w-4 h-4" /> : <Copy className="w-4 h-4" />}
                              </button>
                            </div>
                            <code className="text-xs text-yellow-700 font-mono break-all block">
                              {webhook.signingSecret}
                            </code>
                            <p className="text-xs text-yellow-600 mt-2">
                              Use this secret to verify webhook signatures using HMAC-SHA256
                            </p>
                          </div>
                        )}

                        {formData.authType === 'none' && (
                          <div className="bg-blue-50 border border-blue-200 rounded-lg p-4">
                            <p className="text-sm text-blue-700">
                              No authentication will be used. Your webhook endpoint will receive unsigned requests.
                            </p>
                          </div>
                        )}
                      </div>
                    </div>
                  </div>
                )}
              </div>

              {/* Footer */}
              <div className="border-t border-gray-200 px-6 py-4 bg-gray-50">
                <div className="flex justify-end space-x-3">
                  <button
                    onClick={onClose}
                    disabled={saving}
                    className="px-4 py-2 text-sm font-medium text-gray-700 bg-white border border-gray-300 rounded-md hover:bg-gray-50 disabled:opacity-50"
                  >
                    Cancel
                  </button>
                  <button
                    onClick={handleSave}
                    disabled={saving}
                    className="px-4 py-2 text-sm font-medium text-white bg-purple-600 border border-transparent rounded-md hover:bg-purple-700 disabled:opacity-50 flex items-center"
                  >
                    {saving && (
                      <div className="animate-spin rounded-full h-4 w-4 border-b-2 border-white mr-2"></div>
                    )}
                    {saving ? 'Saving...' : 'Save Changes'}
                  </button>
                </div>
              </div>
            </>
          ) : null}
        </div>
      </div>
    </div>
  );
}