/**
 * Field Registry
 * Central registry for all system-defined fields across entities
 * System fields are code-defined and not stored in Firestore
 */

import { FieldType, EntityScope, FieldValidation } from '../types';

export interface SystemFieldDefinition {
  name: string;
  displayName: string;
  type: FieldType;
  entityScope: EntityScope;
  group?: string;
  validation?: Partial<FieldValidation>;
  order: number;
  description?: string;
  // Metadata flags for special handling
  isAlwaysPresent?: boolean;      // Always exists on entity (id, tenant_id, created_at)
  isAutoGenerated?: boolean;      // Auto-generated/derived (firstName from name)
  isMergedFromExternal?: boolean; // Merged from another collection (phoneNumber)
  isInternal?: boolean;           // Internal fields not meant for user selection (id, tenant_id, created_at, updated_at)
  hideFromUI?: boolean;           // Hide from UI contact detail/conversation pages (but still available in automations)
}

/**
 * Contact System Fields
 * These mirror the actual fields in the contacts collection
 */
const CONTACT_SYSTEM_FIELDS: SystemFieldDefinition[] = [
  // === System Fields (Always Present - Internal, not user-facing) ===
  {
    name: 'id',
    displayName: 'Contact ID',
    type: 'string',
    entityScope: 'contact',
    group: 'System',
    order: 1,
    description: 'Unique identifier for the contact',
    isAlwaysPresent: true,
    isInternal: true,
    validation: { required: true },
  },
  {
    name: 'tenant_id',
    displayName: 'Tenant ID',
    type: 'string',
    entityScope: 'contact',
    group: 'System',
    order: 2,
    description: 'Tenant this contact belongs to',
    isAlwaysPresent: true,
    isInternal: true,
    validation: { required: true },
  },
  {
    name: 'created_at',
    displayName: 'Created At',
    type: 'datetime',
    entityScope: 'contact',
    group: 'System',
    order: 3,
    description: 'When the contact was created',
    isAlwaysPresent: true,
    isInternal: true,
    validation: { required: true },
  },
  {
    name: 'updated_at',
    displayName: 'Updated At',
    type: 'datetime',
    entityScope: 'contact',
    group: 'System',
    order: 4,
    description: 'When the contact was last updated',
    isInternal: true,
  },

  // === User-Facing System Fields ===
  // Add contactId as an alias for id (for automations compatibility)
  {
    name: 'contactId',
    displayName: 'Contact ID',
    type: 'string',
    entityScope: 'contact',
    group: 'Basic Info',
    order: 5,
    description: 'Unique contact identifier',
    isAlwaysPresent: true,
    hideFromUI: true, // Hide from contact details/conversations UI (auto-generated, read-only)
    validation: { required: true },
  },

  // === Basic Info Fields ===
  {
    name: 'name',
    displayName: 'Full Name',
    type: 'string',
    entityScope: 'contact',
    group: 'Basic Info',
    order: 10,
    description: 'Contact full name',
  },
  {
    name: 'firstName',
    displayName: 'First Name',
    type: 'string',
    entityScope: 'contact',
    group: 'Basic Info',
    order: 11,
    description: 'Contact first name (derived from full name)',
    isAutoGenerated: true,
  },
  {
    name: 'lastName',
    displayName: 'Last Name',
    type: 'string',
    entityScope: 'contact',
    group: 'Basic Info',
    order: 12,
    description: 'Contact last name (derived from full name)',
    isAutoGenerated: true,
  },

  // === Contact Info Fields ===
  {
    name: 'email',
    displayName: 'Email',
    type: 'email',
    entityScope: 'contact',
    group: 'Contact Info',
    order: 20,
    description: 'Primary email address',
  },
  {
    name: 'phoneNumber',
    displayName: 'Phone Number',
    type: 'phone',
    entityScope: 'contact',
    group: 'Contact Info',
    order: 21,
    description: 'Primary phone number (merged from contact_addresses collection)',
    isMergedFromExternal: true,
  },
  {
    name: 'channel',
    displayName: 'Channel',
    type: 'string',
    entityScope: 'contact',
    group: 'Contact Info',
    order: 22,
    description: 'Communication channel (SMS, email, etc.)',
  },
  {
    name: 'address',
    displayName: 'Address',
    type: 'string',
    entityScope: 'contact',
    group: 'Contact Info',
    order: 23,
    description: 'Contact address',
  },

  // === Additional Info Fields ===
  {
    name: 'notes',
    displayName: 'Notes',
    type: 'textarea',
    entityScope: 'contact',
    group: 'Additional Info',
    order: 30,
    description: 'General notes about the contact',
  },
  {
    name: 'dateOfBirth',
    displayName: 'Date of Birth',
    type: 'date',
    entityScope: 'contact',
    group: 'Additional Info',
    order: 31,
    description: 'Contact date of birth',
  },
];

/**
 * Get all system fields for a given entity scope
 * @param entityScope - Filter by entity type (contact, opportunity, etc.)
 * @returns Array of system field definitions
 */
export function getSystemFields(entityScope?: EntityScope): SystemFieldDefinition[] {
  if (entityScope === 'contact') {
    return CONTACT_SYSTEM_FIELDS;
  }

  // Future: Add other entity types
  // if (entityScope === 'opportunity') return OPPORTUNITY_SYSTEM_FIELDS;
  // if (entityScope === 'company') return COMPANY_SYSTEM_FIELDS;
  // if (entityScope === 'deal') return DEAL_SYSTEM_FIELDS;

  // If no entityScope provided, return all system fields
  if (!entityScope) {
    return [...CONTACT_SYSTEM_FIELDS];
  }

  return [];
}

/**
 * Check if a field name is reserved as a system field
 * @param name - Field name to check
 * @param entityScope - Entity scope to check within
 * @returns True if the name is reserved
 */
export function isSystemFieldName(name: string, entityScope: EntityScope): boolean {
  return getSystemFields(entityScope).some((f) => f.name === name);
}

/**
 * Get a specific system field by name
 * @param name - Field name
 * @param entityScope - Entity scope
 * @returns System field definition or undefined
 */
export function getSystemField(
  name: string,
  entityScope: EntityScope
): SystemFieldDefinition | undefined {
  return getSystemFields(entityScope).find((f) => f.name === name);
}

/**
 * Get all reserved field names for an entity scope
 * @param entityScope - Entity scope
 * @returns Array of reserved field names
 */
export function getReservedFieldNames(entityScope: EntityScope): string[] {
  return getSystemFields(entityScope).map((f) => f.name);
}
